# Generated by Django 5.1.6 on 2025-03-24 22:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('legalservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='gid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('abc770dc-47f5-4888-aaa1-a00dcce4d559'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='firmstaffprofile',
            name='gid',
            field=models.UUIDField(default=uuid.UUID('dcfdee4e-853c-4944-92d8-f73597a0a3e4'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='gid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('7c73d4f2-5701-4d35-a5e9-372e4ef663fe'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='organisationprofile',
            name='gid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('9592679b-9fa1-4df9-a62c-3ac4ed267206'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gid',
            field=models.UUIDField(default=uuid.UUID('776145f2-4801-4d19-a869-d6ad06025184'), editable=False, unique=True),
        ),
    ]
