# Generated by Django 5.1.6 on 2025-04-13 19:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legalservice", "0002_emergency_content_type_alter_emergency_gid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergency",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="emergency",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("2068719c-1df4-497d-a165-4206368e080f"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="firmstaffprofile",
            name="gid",
            field=models.UUIDField(
                default=uuid.UUID("322ce91c-ee85-4b1b-ac10-26c33b04bd42"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="individualprofile",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("3a1b7045-5277-4b4f-87f2-20a503f7a98c"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationprofile",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("5cc9b418-0a79-4a8c-981e-98dfcb7994e7"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gid",
            field=models.UUIDField(
                default=uuid.UUID("a8168fd1-7839-4ddd-9ae8-3fd3007ce7e7"),
                editable=False,
                unique=True,
            ),
        ),
    ]
