# Generated by Django 5.2.2 on 2025-06-08 10:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "legalservice",
            "0003_alter_emergency_created_at_alter_emergency_gid_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergency",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("b0f94512-ed86-48d1-8d7c-b25988f20cc8"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="firmstaffprofile",
            name="gid",
            field=models.UUIDField(
                default=uuid.UUID("af3241b1-3f7d-4201-8b77-c075a00887b5"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="individualprofile",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("3b3adc4f-fa0c-4f09-a7c5-26e1cde90594"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationprofile",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("54b89dc1-62a7-4fe1-8c9a-13fda77fa5dc"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gid",
            field=models.UUIDField(
                default=uuid.UUID("cab24153-15fc-47b0-ba76-c87cc6719e45"),
                editable=False,
                unique=True,
            ),
        ),
    ]
