# Generated by Django 5.2.2 on 2025-07-06 11:24

import django.db.models.deletion
import legalservice.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "legalservice",
            "0004_alter_emergency_gid_alter_firmstaffprofile_gid_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftingAffidavit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("case_summary", models.TextField()),
                ("is_closed", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "gid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.UUID("e57d9d24-baed-4959-9f88-42c3d6d715bf"),
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "ref_number",
                    models.CharField(
                        default=legalservice.models.generate_ref_number,
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DraftingAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("case_summary", models.TextField()),
                ("is_closed", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "gid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.UUID("e57d9d24-baed-4959-9f88-42c3d6d715bf"),
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "ref_number",
                    models.CharField(
                        default=legalservice.models.generate_ref_number,
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FamilyMatter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("case_summary", models.TextField()),
                ("is_closed", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "gid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.UUID("e57d9d24-baed-4959-9f88-42c3d6d715bf"),
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "ref_number",
                    models.CharField(
                        default=legalservice.models.generate_ref_number,
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LabourLaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("case_summary", models.TextField()),
                ("is_closed", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "gid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.UUID("e57d9d24-baed-4959-9f88-42c3d6d715bf"),
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "ref_number",
                    models.CharField(
                        default=legalservice.models.generate_ref_number,
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LandMatter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("case_summary", models.TextField()),
                ("is_closed", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "gid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.UUID("e57d9d24-baed-4959-9f88-42c3d6d715bf"),
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "ref_number",
                    models.CharField(
                        default=legalservice.models.generate_ref_number,
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LegalAdvice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("case_summary", models.TextField()),
                ("is_closed", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "gid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.UUID("e57d9d24-baed-4959-9f88-42c3d6d715bf"),
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "ref_number",
                    models.CharField(
                        default=legalservice.models.generate_ref_number,
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OtherMatter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("case_summary", models.TextField()),
                ("is_closed", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "gid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.UUID("e57d9d24-baed-4959-9f88-42c3d6d715bf"),
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "ref_number",
                    models.CharField(
                        default=legalservice.models.generate_ref_number,
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="RefNumber",
        ),
        migrations.AlterField(
            model_name="emergency",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("e57d9d24-baed-4959-9f88-42c3d6d715bf"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="emergency",
            name="ref_number",
            field=models.CharField(
                default=legalservice.models.generate_ref_number,
                max_length=10,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="firmstaffprofile",
            name="gid",
            field=models.UUIDField(
                default=uuid.UUID("8366549b-7adc-4342-9ac3-0a81f322d588"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="individualprofile",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("3531a4d3-4711-4dc7-b418-f604f0521663"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationprofile",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("ee1b759e-7ad9-4d2f-851b-0d89019a0fe2"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gid",
            field=models.UUIDField(
                default=uuid.UUID("3e8bb30e-2b2c-4504-8408-e075cee18859"),
                editable=False,
                unique=True,
            ),
        ),
    ]
