# Generated by Django 5.2.2 on 2025-07-06 18:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legalservice", "0007_remove_organisationprofile_contact_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftingaffidavit",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("40675f07-f3f8-441b-8f73-0dd7a4546c25"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="draftingagreement",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("40675f07-f3f8-441b-8f73-0dd7a4546c25"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="emergency",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("40675f07-f3f8-441b-8f73-0dd7a4546c25"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="familymatter",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("40675f07-f3f8-441b-8f73-0dd7a4546c25"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="firmstaffprofile",
            name="gid",
            field=models.UUIDField(
                default=uuid.UUID("67aac926-353d-4ebe-b9d6-b2fbf948693a"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="individualprofile",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("6b099f7a-3d27-4b6d-83ed-d041c7756e87"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="labourlaw",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("40675f07-f3f8-441b-8f73-0dd7a4546c25"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="landmatter",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("40675f07-f3f8-441b-8f73-0dd7a4546c25"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="legaladvice",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("40675f07-f3f8-441b-8f73-0dd7a4546c25"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationprofile",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("16ee61a0-3930-43f3-9eb1-ccf158f98165"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="othermatter",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("40675f07-f3f8-441b-8f73-0dd7a4546c25"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
