# Generated by Django 5.2.2 on 2025-07-12 18:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legalservice", "0008_alter_draftingaffidavit_gid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftingaffidavit",
            name="gid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="draftingagreement",
            name="gid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="emergency",
            name="gid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="familymatter",
            name="gid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="firmstaffprofile",
            name="gid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="individualprofile",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("4ba37e40-0b82-4922-a4f4-5f9e00a8b3e9"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="labourlaw",
            name="gid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="landmatter",
            name="gid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="legaladvice",
            name="gid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationprofile",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("0e1e46ae-5514-4cea-99a7-8a20eaff95b1"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="othermatter",
            name="gid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
