# Generated by Django 5.2.2 on 2025-07-17 07:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legalservice", "0009_alter_draftingaffidavit_gid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseTray",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("acknowledged", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="firmstaffprofile",
            name="bar_association_number",
        ),
        migrations.AlterField(
            model_name="individualprofile",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("31e259af-a741-4f3e-84cd-f3f5bc77c8c3"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationprofile",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("fb6765d5-204e-4c04-8e8c-08a975e7cd29"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="draftingaffidavit",
            name="tray",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="legalservice.casetray",
            ),
        ),
        migrations.AddField(
            model_name="draftingagreement",
            name="tray",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="legalservice.casetray",
            ),
        ),
        migrations.AddField(
            model_name="emergency",
            name="tray",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="legalservice.casetray",
            ),
        ),
        migrations.AddField(
            model_name="familymatter",
            name="tray",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="legalservice.casetray",
            ),
        ),
        migrations.AddField(
            model_name="labourlaw",
            name="tray",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="legalservice.casetray",
            ),
        ),
        migrations.AddField(
            model_name="landmatter",
            name="tray",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="legalservice.casetray",
            ),
        ),
        migrations.AddField(
            model_name="legaladvice",
            name="tray",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="legalservice.casetray",
            ),
        ),
        migrations.AddField(
            model_name="othermatter",
            name="tray",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="legalservice.casetray",
            ),
        ),
    ]
