# Generated by Django 5.2.2 on 2025-07-17 07:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legalservice", "0010_casetray_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="casetray",
            name="name",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="individualprofile",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("444cca14-c601-408b-9a32-088a4db92c26"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationprofile",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("817ad41b-6114-4f25-af0a-aecc50889dec"),
                editable=False,
                unique=True,
            ),
        ),
    ]
