# Generated by Django 5.2.2 on 2025-07-21 09:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legalservice", "0011_casetray_name_alter_individualprofile_gid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individualprofile",
            name="gid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="organisationprofile",
            name="gid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("b4dfe2ba-bb90-4705-978e-e7760cb4dba6"),
                editable=False,
                unique=True,
            ),
        ),
    ]
